# Generated by Django 5.0.2 on 2024-02-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_utilisateur_adresse_utilisateur_pays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_postal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
