# Generated by Django 5.0.2 on 2024-02-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_utilisateur_code_postal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='pays',
        ),
    ]
