# Generated by Django 5.0.2 on 2024-04-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_utilisateur_pays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
