# Generated by Django 5.0.2 on 2024-02-12 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.JSONField(default=list)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categorie')),
                ('images', models.ManyToManyField(related_name='produits', to='shop.image')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.marque')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reduction', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='shop.categorie')),
                ('produits', models.ManyToManyField(blank=True, related_name='promotions', to='shop.produit')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.promotion'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['nom', 'categorie'], name='shop_produi_nom_a821db_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['prix'], name='shop_produi_prix_4184db_idx'),
        ),
    ]
