# Generated by Django 5.0.2 on 2024-02-12 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_produit_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='images',
        ),
        migrations.AddField(
            model_name='image',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.produit'),
        ),
    ]
