# Generated by Django 5.0.2 on 2024-02-14 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_produit_image_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='produits',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='promotion',
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['nom'], 'verbose_name': 'categorie', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='marque',
            options={'ordering': ['nom'], 'verbose_name': 'marque', 'verbose_name_plural': 'marques'},
        ),
        migrations.RemoveIndex(
            model_name='produit',
            name='shop_produi_nom_a821db_idx',
        ),
        migrations.RemoveIndex(
            model_name='produit',
            name='shop_produi_prix_4184db_idx',
        ),
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='marque',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/marques'),
        ),
        migrations.AddField(
            model_name='marque',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='ajouter',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='produit',
            name='modifer',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/produits/%Y/%m/%d/'),
        ),
        migrations.AddIndex(
            model_name='categorie',
            index=models.Index(fields=['nom'], name='shop_catego_nom_e078ae_idx'),
        ),
        migrations.AddIndex(
            model_name='marque',
            index=models.Index(fields=['nom'], name='shop_marque_nom_506dde_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['id', 'slug'], name='shop_produi_id_b3cdb3_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['nom'], name='shop_produi_nom_deab34_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['-ajouter'], name='shop_produi_ajouter_945236_idx'),
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
    ]
