# Generated by Django 5.0.2 on 2024-02-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_promotion_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/marques/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/produits/%Y/%m/%d/'),
        ),
    ]
