# Generated by Django 5.0.2 on 2024-02-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_marque_image_alter_produit_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='quantite',
        ),
    ]
