# Generated by Django 5.0.2 on 2024-02-14 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_produit_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='marque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.marque'),
        ),
    ]
