# Generated by Django 5.0.2 on 2024-02-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_categorie_marque_marque_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='modifer',
            new_name='modifier',
        ),
        migrations.AddField(
            model_name='produit',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
