# Generated by Django 5.0.2 on 2024-02-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_modifer_produit_modifier_produit_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/categories/%Y/%m/%d'),
        ),
    ]
