# Generated by Django 5.0.2 on 2024-02-17 00:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_categorie_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['modifier']},
        ),
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(null=True, upload_to='images/produits/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, null=True)),
                ('taux_de_reduction', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ajouter', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifier', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['modifier'],
                'indexes': [models.Index(fields=['nom'], name='shop_promot_nom_dc7fb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(null=True)),
                ('date_fin', models.DateTimeField(null=True)),
                ('produit', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.produit')),
                ('promotion', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.promotion')),
            ],
            options={
                'ordering': ['date_fin'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='promotion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.promotion'),
        ),
    ]
