# Generated by Django 5.0.2 on 2024-02-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('shop', '0013_alter_produit_description_alter_produit_promotion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContenuC',
            new_name='CommandeItems',
        ),
    ]
