# Generated by Django 5.0.2 on 2024-02-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_contenuc_commandeitems'),
        ('shop', '0013_alter_produit_description_alter_produit_promotion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommandeItems',
            new_name='CommandeItem',
        ),
    ]
